name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK & NDK licenses
      run: |
        yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
        sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.13846066" "cmake;3.22.1" "platforms;android-35" "build-tools;35.0.0"

    - name: Create custom debug keystore
      run: |
        keytool -genkeypair -v -keystore debug.keystore -storepass android -keypass android -alias androiddebugkey \
        -keyalg RSA -keysize 2048 -validity 10000 \
        -dname "CN=Android Debug,O=Android,C=US"
        mkdir -p ~/.android
        mv debug.keystore ~/.android/debug.keystore

    - name: Grant Gradle permissions
      run: chmod +x gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace --no-daemon

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: NewBlackbox-debug
        path: app/build/outputs/apk/debug/*.apk
